name: Build Dentist APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Tools
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        # لێرەدا فەرمانی دروستکردنی کلیل و ئیمزاکردنی بۆ زیاد دەکەین تا فایلەکە دروست بێت
        run: |
          yes | bubblewrap init --manifest=manifest.json --no-prompt || true
          yes | bubblewrap build --no-prompt --skipFirstRunCheck || true
          
      - name: Find and Move APK
        # ئەم دێڕە فایلەکە دەدۆزێتەوە و دەیهێنێتە بەردەست
        run: |
          find . -name "*.apk" -exec cp {} . \;
          ls *.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Dentist-App
          path: ./*.apk
          if-no-files-found: error
